### ISSUE TITLE
license compatability

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [maxmind/libmaxminddb#122]
license incompatibility is [preventing wireshark from using libmaxminddb for GeoLite2 support](https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=10658). Is there anything that can be done about it? Thanks

**Comment by geraldcombs** [comment]
As discussed in the bugs.wireshark.org link, Wireshark is released under the GPL version 2.0 or later and libmaxminddb is released under the Apache 2.0 license. The FSF considers them incompatible: https://www.gnu.org/licenses/license-list.en.html#apache2

If there is an alternate library that we can use to read MaxMind DB files or another path forward we'd love to hear about it.

**Comment by paravoid** [comment]
The GPLv2 is not compatible with Apache 2.0, but the GPLv3 is, so technically "GPLv2 or later" is as well. In any case, not a libmaxminddb issue I'd say.

**Comment by geraldcombs** [comment]
@paravoid You're absolutely correct that this is a Wireshark issue and not a libmaxminddb issue. However, I'd prefer that we move from GPLv2+ to GPLv3+ based on the consensus of our community, not because we were forced to by a third party library.

**Comment by paravoid** [comment]
(first of all: I'm not affiliated with MaxMind and I'm not authoritative on this subject)

That's fair, but it'd also be fair to say that libmaxminddb would like to choose its license based on their needs (e.g. Apache2/GPLv3's patent protection) and not because they're forced by a third party project that wants to link against it :)

Regardless, my comment was not about *re*licensing. Wireshark is already licensed with an "or later" clause and therefore AIUI, and thus it's already licensed in a way where one could link against libmaxminddb without violating either project's copyright, assuming no GPLv2-only code made it into the build. Downstream distributors (e.g. Linux distributions) could make this call and produce a legally distributable bundle.

**Comment by oschwald** [comment]
Thanks for raising this. We did look into this internally. We don't plan on changing the license at this time.

It looks like Wireshark was able to come up with a suitable workaround in the meantime.
