### ISSUE TITLE
How to link libmaxminddb to my c++ application

### ISSUE THREAD

**Issue by Mahmoud-Alsayed** [maxmind/libmaxminddb#146]
I want to use this library as a shred library in my application.
My project is a cross-platform wxWidgets project built with TDM GCC.
Is there any way to compile this project to shared library and link it in my project?

**Comment by Mahmoud-Alsayed** [comment]
I installed the maxminddb on my Ubuntu VM, and then copied the resulted .a lib to my project 'I'm working on this project in a Windows system'. I included the `maxminddb.h` and `maxminddb_config.h`. But when I compile I get  these error messages:
```
undefined reference to `MMDB_close'
undefined reference to `MMDB_open'
undefined reference to `MMDB_strerror'
```
Also, I tried to compile using Visual Studio, I get the same error messages after linking the `.lib` file.
The project I'm working on is `c++ wxWidgets` I'm using `Code::Blocks` as IDE and `TDM GCC` as compiler.

**Comment by horgh** [comment]
I'm not familiar with TDM GCC. We have some info about working with Visual Studio [here](https://github.com/maxmind/libmaxminddb/tree/master/projects/VS12).

The errors you show indicate this library isn't being linked in. Including the headers won't be sufficient. You also need to do something like pass `-lmaxminddb` when linking. Given TDM GCC looks like a modified GCC, I'd expect that flag to work, assuming it can find the `.a`, though I think you'll need to compile the `.a` in Windows.

**Comment by Mahmoud-Alsayed** [comment]
I've compile the VS projects, three files produced `libtap.lib` `libmaxminddbd.lib` and `test_maxminddb_test_helper.lib`. I've linked these two files `libtap.lib` `libmaxminddbd.lib`. I'm still getting the same error. Any ideas?

**Comment by horgh** [comment]
You won't need `libtap`. That's used for the tests.

Are you compiling this library and your application with the same compiler? It sounds like this is the case, but it crossed my mind to confirm.

Another thought might be whether this library is getting compiled as C++. You'll want it compiled as C, and then when linking to C++ code, it will find the symbols due to us wrapping the functions with `extern "C"`, as described [here](https://stackoverflow.com/questions/2238456/how-does-cs-extern-work). If instead it's compiled as C++, then included in your C++ application with the `extern "C"`, it's possible it will look for the wrong symbols.

I might suggest creating a simple C library and figuring out how to get that linked in. Doing this could rule out any complications from working with an external project. Once that works, you could apply the same techniques to hopefully get this one working.

I'm not sure what else to suggest!
