### ISSUE TITLE
Compile libmmaxminddb 1.3.2 in AIX 7.1

### ISSUE THREAD

**Issue by hmtorres** [maxmind/libmaxminddb#169]
Hello,

I try to compile the **libmmaxminddb** in **AIX 7.1** and i have a trouble with a make step.

The problem is in the **mmdblookup.c** (line #include <getopt.h>) because in AIX the **getopt_long()** doesn't exist and only support to **getopt()** (#include <unistd.h>)

Can your help me with this problem?

I Attach the logs with the [output](https://github.com/maxmind/libmaxminddb/files/1926976/output.log).

Thank you.

**Info**:
* GCC Version: 6.3.0
* AIX Version: 7.1
* libmaxminddb Version: 1.3.2

**References**:
https://stackoverflow.com/questions/34044975/getopt-h-missing-in-aix-7-1
https://github.com/luaposix/luaposix/issues/245
https://www.ibm.com/support/knowledgecenter/en/ssw_aix_71/com.ibm.aix.basetrf1/getopt.htm

**Comment by horgh** [comment]
If you mainly need the library, you could try excluding `mmdblookup` from the build: `./configure --disable-binaries` should do it.

Making `mmdblookup` fall back to `getopt()` if `getopt_long()` or `getopt.h` are not available would probably be possible. Ideally we'd still use the latter if it is available in order to continue supporting the existing flags. We'd likely accept a patch for this, but probably will not get to it soon ourselves.

**Comment by hmtorres** [comment]
I test the build with: `./configure --disable-tests --disable-binaries` and works.

Thanks for your help!
