### ISSUE TITLE
Feature Request - Maximize Efficiency with Daemon Process

### ISSUE THREAD

**Issue by knoxcard** [maxmind/libmaxminddb#188]
Is there anyway to run this as a background daemon process and simply have consecutive calls thereafter to query IP addresses?  It seems like a major drain on resources to have to open/close/process the large .mmdb file every single time per call.  Thoughts anyone?

**Server Background Daemon Process**
mmdblookup --daemon --file=<maxmind.mmdb file>

 **Simply call this only, will error out if mmdblookup daemon proces is not running** 
mmdblookup --ip 127.0.0.1

 **exit daemon** 
mmdblookup shutdown or killall mmdblookup

**Comment by horgh** [comment]
Yes, it's not efficient to use mmdblookup if you're planning on looking up many IPs.

Something like what you describe sounds like it could be useful! However it's not likely we'd extend mmdblookup this way. mmdblookup is intended to be a tool for development, such as to help integrators inspect databases, rather than as a way to perform lookups in a production environment.

For your use case you could consider building a small HTTP service using one of the higher level MMDB reader libraries.

**Comment by PatrickCronin** [comment]
_Digging up the past a bit, but for posterity:_

We have recently released  [https://github.com/maxmind/mmdbinspect](`mmdbinspect`) which is a new tool intended to address several of the issues people raised relating to the general usability of `mmdblookup`. It supports querying multiple databases and multiple IPs with a single incantation, and it outputs pure JSON.

While the intent of `mmdblookup` was and is to support developers who are integrating libmaxminddb or other reader libraries into their applications, `mmdbinspect` is intended to be a well-behaved command line program supporting general purpose querying of MMDB databases.

It's in beta. We would welcome you to try it and provide any feedback you may have on its issues page.
