### ISSUE TITLE
$make command Warning

### ISSUE THREAD

**Issue by Barnabas2** [maxmind/libmaxminddb#297]
I get the following warning when running the $make command

```
WARNING: 'aclocal-1.16' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <https://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/autoconf>
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>
make: *** [Makefile:412: aclocal.m4] Error 127

```
Do I really need to install GNU Autoconf, GNU m4 and Perl in order for the $make command to work?

**Comment by oschwald** [comment]
Can you share the exact commands you are running? It sounds like you are trying to regenerate the build files using the `./bootstrap` script. Perhaps you downloaded the GitHub generated "Source code" archive rather than the `libmaxminddb-*.tar.gz` file, which has the build files already generated.

As mentioned in the documentation, we provide CMake build files as well if the autotool ones are not available on your platform.

**Comment by Barnabas2** [comment]
@oschwald thanks for the instrutions. I had to install automake first it seems using `sudo apt-get install automake` for the make function to run. I then downloaded the `libmaxminddb-*.tar.gz`  file and installation thereafter was smooth.
