### ISSUE TITLE
Which is most reliable for locating a city

### ISSUE THREAD

**Issue by fxfactorial** [maxmind/libmaxminddb#94]
Several questions/issues. 

I'm looking for the most reliable way to map an IP address to a city and I think the following is inconsistent. 
(Using the GeoIP2 free version for cities)

Say you have let "69.12.169.82" as the ip. For this IP, maxminddb gives a city value of Santa Rosa, CA. This is off mark and its north of where I actually am, San Francisco. The zipcode produced, 95408, is also off mark and is about as far south of me as Santa Rosa is north of me. 

So the zipcode and city are not agreeing. Is this because I'm using the free version? And even so, one would think the two would agree, zip code and city. 

Also, which one is more reliable? My goal is to get the closest "big" city to the IP, I want to the functionality that websites like yelp offer when you first come to their site. 

Also, I gave an IP that was from Russia but I got a postal code that looked like an American Code. Are postal codes only reliable for US based IPs? 

(Coding note, I don't do too much C but I do love ocaml...which leads me to ask why aren't all the MMDB_DATA_TYPE_* just an enum rather than #defines. I want exhaustiveness from switch statements.)

**Comment by oschwald** [comment]
I am not sure offhand why the zip code and city do not agree in that case. Our precision database has San Francisco, CA, 94103 for that IP. There may be a data quality issue with our source data causing the conflicting information. Generally, the postal code will be more specific than the city, but it should be in the appropriate city. You may have better luck contacting support@maxmind.com. You can also [submit a correction](https://support.maxmind.com/geoip-data-correction-request/).

I am also not sure why macro definitions were used instead of an enum. We do use enums for the APIs in some other languages.
